version: '3.8'

services:
  # Módulo 1 - Inventario (.NET)
  inventario-api:
    build: ./inventario-api
    container_name: inventario_api
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=100.107.111.1
      - DB_USER=dda_user
      - DB_PASSWORD=secret
      - DB_NAME=sistema_industrial
    networks:
      - red_industrial

  # Módulo 3 - Logística (Python)
  logistica-api:
    build: ./logistica-api
    container_name: logistica_api
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=100.107.111.1
      - DB_USER=dpt_user
      - DB_PASSWORD=secret
      - DB_NAME=sistema_industrial
    networks:
      - red_industrial

  # Microservicio QR (Node.js)
  trazabilidad-qr:
    build: ./trazabilidad-qr
    container_name: trazabilidad_qr
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=100.107.111.1
      - DB_USER=qr_user
      - DB_PASSWORD=secret
      - DB_NAME=sistema_industrial
    networks:
      - red_industrial

networks:
  red_industrial:
    external: true

